//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicDay.BusinessLogic.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public System.Guid ProductImageID { get; set; }
        public System.Guid ProductID { get; set; }
        public byte ImageNo { get; set; }
        public string ImageDesciption { get; set; }
        public byte[] Image { get; set; }
        public byte[] ImageThumbnail { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
